### ISSUE TITLE
New images

### ISSUE THREAD

**Issue by TiToMoskito** [MaxAndolini/hCaptcha-Images#1]
Is it possible to update this repo or give us a tip how to download those by ourself?

**Comment by MaxAndolini** [comment]
I already update it from time to time.  It's a bit difficult to separate them, after I download the images with the help of bot, I delete the duplicates with the script, then I check myself and delete the irrelevant images. Just one thing missing right now as a newcomer "airplanes in the sky that are flying to the right".

**Comment by TiToMoskito** [comment]
Okay no problem, i thought you have a bot which separates them by itself. Someone told me, that there are new images with dogs. I will take a look at it, and if i found those, i will make a pull request to help you :)

**Comment by MaxAndolini** [comment]
Text me on Discord maxandolini#9216
